### ISSUE TITLE
Change the way `simulation.Node` works

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#104]
Now: `simulation.Node` is called at startup of each conode
Wanted: `simulation.Node` is called once all nodes are available

Proposition: in the root-conode, after the counting, make a `broadcast`-protocol that calls all `simulation.Node`s.
https://github.com/dedis/onet/blob/master/simul/platform/runsimul.go#L102

Proposition2: improve `Counter`-protocol so that it doesn't fail that easily if not all nodes are there and has a final "all is OK" message that the children nodes can listen to and call `simulation.Node`.

**Comment by nikkolasg** [comment]
I'm more for proposition 1.

**Comment by ineiti** [comment]
that's what I did in the PR.
