### ISSUE TITLE
GlobalProtocolRegister - usability

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#120]
Now: `GlobalProtocolRegister` stores a new protocol in the global pool that will be copied to every `Server` instantiated. 

Problem: It is possible to call `GlobalProtocolRegister` _after_ the instantiation of a server, which will have a non-desired effect: the protocol is not available in the already instantiated `Server`s

Proposition: add a flag to the `protocolStorage` indicating a `Server` has already been started, and `Fatal` if `GlobalProtocolRegister` is called afterwards.

Caveat: for tests, a `Local.Close` must clear the flag, so that next tests will run fine

**Comment by ineiti** [comment]
This might be made redundant with the configuration-issue config.v2.

**Comment by jeffallen** [comment]
Goal: give early, clear crash/error so that students don't fall into this trap.
