### ISSUE TITLE
mininet-simulation

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#124]
Some issues with mininet:
- `setup_iccluster.sh` doesn't find `install_mininet.sh`
- `simul -platform mininet` should ask if it's for iccluster, take the names and run `setup_iccluster.sh`

**Comment by christophebertrand** [comment]
what should happen if it is not for iccluster?

**Comment by ineiti** [comment]
Have a choice at the beginning:

Is this for ICCluster?
(yes) - get iccluster-numbers
(no) - get server-names
