### ISSUE TITLE
Remove `onet.crypto.SignSchnorr`

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#142]
V2:
remove `onet.crypto.SignSchnorr` and use the one in `crypto` instead.

**Comment by nikkolasg** [comment]
Crypto has now a `sign.Schnorr` available so ideally, we should delete that in onet.

**Comment by ineiti** [comment]
OK, sounds good. But for compatibility reasons we probably cannot remove this schnorr-signature before v2.

**Comment by jeffallen** [comment]
Was done with #240.
