### ISSUE TITLE
[Network] Address.Valid() only for tcp

### ISSUE THREAD

**Issue by nikkolasg** [dedis/onet#149]
`address.Valid()` & `address.ConnType()` only returns the right information for `TCP` based connections but not for `Local`.

**Comment by kc1212** [comment]
Is there an example/test for when this issue occurs?

I tried adding
```go
	if !listener.addr.Valid() {
		t.Error("address not valid")
	}
```
to the `TestLocalListener` test and it seemed fine.

**Comment by nikkolasg** [comment]
Not a real practical issue, more a consistency issue. Ideally it should be correct, and I did not check the code so maybe it's already ok :)

**Comment by jeffallen** [comment]
Hard to see what's to really fix here. Closing, but if @nikkolasg can explain better, please reopen.
