### ISSUE TITLE
[Simulation] Lots of late message for TreeNodeInstance

### ISSUE THREAD

**Issue by nikkolasg** [dedis/onet#157]
Lately, for all simulations, lots of people complained about the fact that he following message:
```
Message for TreeNodeInstance already finished
```
is appearing a *lot*, like taking the full buffer of the terminal sometimes.
This was not the case before, and we need to figure out why. It may be the protocol to sync up at the beginning/end of the simulation.
For the moment, I've put it in`log.Lvl5` as a quick fix in this PR https://github.com/dedis/onet/pull/156

**Comment by ineiti** [comment]
IIRC, this is due to the fact that the count-protocol does not behave nicely when it has to restart. I think this was one of the reasons I wanted to rewrite it ;)

**Comment by nikkolasg** [comment]
Ok sure. But why did we not see this message before *as much* ?

**Comment by jeffallen** [comment]
This is as designed, for better or worse.
