### ISSUE TITLE
It should be possible to control the net.Listen() address

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#176]
Now: `NewTCPListener` in `onet/network/tcp.go` always binds globally.

Problems: 
- for a good firewall, an app trying to bind globally is refused
- not globally binding doesn't work when the nodes are running in a virtual machine

Proposed solution:
- `NetTCPListener` checks the address: if it's a private address, it binds to it, if it's a public address, it binds globally. Use `Address.Public()` to decide if it's public or not.

**Comment by jeffallen** [comment]
Probably need a new optional field in private.toml telling the server where to listen. If not set, then listen on 0.0.0.0.

**Comment by ineiti** [comment]
Add a `ListenAddress` entry to `private.toml` containing the address and port to listen on. If `ListenAddress` is missing, then listen on `0.0.0.0` and port given by `Address`.
