### ISSUE TITLE
service-data saving

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#192]
When the data gets big (>10MB), the saving-process blocks everything. Should we:

- start using some database?
- learn how to save incrementally?
- copy the data and save in a go-routine?

**Comment by nikkolasg** [comment]
At this point we may want to learn from other crypto currencies how they are doing it. Especially ethereum since they store the whole state as well.

**Comment by nikkolasg** [comment]
Related discussion about zcash: they're thinking of switching of data storage. From what I understood they had berkelyDB and they may be willing to switch to sqlite db ;)
https://github.com/zcash/zcash/issues/2221

**Comment by ineiti** [comment]
Done - thanks to @kc1212
