### ISSUE TITLE
[simul] Infinite loop with specific toml values

### ISSUE THREAD

**Issue by nikkolasg** [dedis/onet#210]
With the TOML file:
```go
Simulation = "PedersenDKG"
Servers = 1
Hosts = 7
Bf = 1
Rounds = 10
```

The `calcHosts` function in `simul/build.go` is running in an infinite loop.

**Comment by ineiti** [comment]
Yes, he's trying to fit the hosts in a non-overlapping way on 1 server - no wonder he doesn't manage too ;)

**Comment by nikkolasg** [comment]
Well on my computer it made an infinite loop. I did not really try to understand the underlying reason though !

**Comment by ineiti** [comment]
Did you find where the infinite loop is done? Because `calcHosts` in your example will do a division by zero. But I can think of another place where it tries to distribute the hosts on different servers, where it might fail.

**Comment by ineiti** [comment]
Looking through https://github.com/dedis/onet/blob/master/tree.go#L425 however I think it should work even with a single server.

**Comment by ineiti** [comment]
I tested `GenerateBigNaryTree` and it does indeed work with 1 server and/or 1 host and a BF of 1.

**Comment by nikkolasg** [comment]
Sorry, the place where the infinite loop happens is there https://github.com/dedis/onet/blob/master/simul/build.go#L253

**Comment by nikkolasg** [comment]
I leave this one open, I'll try again if the loop is still there or no.
