### ISSUE TITLE
Simulation: finish test always by closing Monitor

### ISSUE THREAD

**Issue by nikkolasg** [dedis/onet#220]
In `simul/build.go:211`, the prints that the test is finished without errors but do not close the monitor with `monitor.Close()`. Since the end of the test depends on the end of the `monitor.Listen()`, caused the call of `monitor.Close()`, if all is well, the test will never return and timeout and not writing the values into the result csv file.

**Comment by ineiti** [comment]
Is `monitor.Stop()` enough? Because this is called.

**Comment by ineiti** [comment]
Nope, `monitor.Stop` is only called in the failure-path - how did this ever work?

**Comment by ineiti** [comment]
It worked because the remote monitors closed a connection and this is enough to close the monitor.
