### ISSUE TITLE
Cardinality of the Elliptic Curve

### ISSUE THREAD

**Issue by froelich** [dedis/onet#256]
Would it be possible to add a function to get the cardinality of the elliptic curve that is used ?

**Comment by jeffallen** [comment]
Can you add more details like, "in order to do this, I need this". Is the cardinality for a given curve fixed? It seems more like an attribute of the underlying field, right?

In any case, once we've decided what to do, we'll move this over to the kyber repo, where it will really happen.

**Comment by ineiti** [comment]
This should be in kyber, not onet.

**Comment by jeffallen** [comment]
See dedis/kyber#259.
