### ISSUE TITLE
Method TreeNodeInstance.Done() calls multiple Shutdown() on the same node

### ISSUE THREAD

**Issue by Racater** [dedis/onet#257]
In `treenode.go`, the method `Done()` calls multiple time the `Shutdown()` function on the same node, via a double call to `CloseDispatch()`:
- one time at line 524
- the second time at line 554 via `n.overlay.nodeDone(n.token)` and `o.nodeDelete(tok)` then line 505 of `overlay.go`

This causes the `closeDipsatch()` function to call each time the `Shutdown()` function on the same node, effectively calling it multiple time on the same node. This may be problematic, since it may causes multiple deletions errors (multiple closing of channels, etc.).

One solution would be to remove the line 524, even though I don't know the code enough to be 100% sure it'll be safe.

**Comment by ineiti** [comment]
`Done()` has two ways of calling `Shutdown`:
- `closeDispatch` -> `Shutdown`
- `nodeDone` -> `nodeDelete` -> `closeDispatch` -> `Shutdown`

so the main question is why is `closeDispatch` called twice here?
