### ISSUE TITLE
react correctly when different ServerIdentities have the same public key

### ISSUE THREAD

**Issue by jeffallen** [dedis/onet#272]
As Christian noticed, when multiple servers connect with the same public key, things break in confusing ways, because some data structures are keyed by serverID and some by public key.

It is not clear if this should be allowed at all.

**Comment by jeffallen** [comment]
ServerIdentity.ID is a uuid based on the public key:

```go
func NewServerIdentity(public kyber.Point, address Address) *ServerIdentity {
	url := NamespaceURL + "id/" + public.String()
	return &ServerIdentity{
		Public:  public,
		Address: address,
		ID:      ServerIdentityID(uuid.NewV5(uuid.NamespaceURL, url)),
	}
}
```

So this issue must be about something else. @ChristianMct can you give more details on what you saw happening and what should have happened?

**Comment by ChristianMct** [comment]
My observation was that for a binary Tree with 7 nodes having the same public key, the leaf nodes were failing to communicate to send messages back to their parents. Unfortunately, I had no time to instigate more at this point and preferred generating different keys for each nodes.

Can this have something to do with this method:
```go
func (tm *TreeMarshal) MakeTreeFromList(parent *TreeNode, el *Roster) *TreeNode {
	idx, ent := el.Search(tm.ServerIdentityID)
	tn := &TreeNode{
		Parent:         parent,
		ID:             tm.TreeNodeID,
		ServerIdentity: ent,
		RosterIndex:    idx,
	}
	for _, c := range tm.Children {
		tn.Children = append(tn.Children, c.MakeTreeFromList(tn, el))
	}
	return tn
}
```
Apparently, it is calling the `Roster.Search` to retrieve one node's `ServerIdentity`. It looks like this function would always return the first `Roster.List` element if all public keys (i.e. ServerIdentityID, as @jeffallen pointed out), so It might cause problems.

**Comment by jeffallen** [comment]
We won't fix this because it was a test config that is not supported. Will investigate this more in #308.
