### ISSUE TITLE
Rate control on roster creation

### ISSUE THREAD

**Issue by jeffallen** [dedis/onet#273]
Any given server-to-server connection should be rate-limited in it's ability to consume resources (which resources? Rosters? Trees?) on the target server.

Add expiration logic to Roster cache.
Add expiration logic to Tree cache.

**Comment by jeffallen** [comment]
In PR #483, @Gilthoniel did the expiration. Now we need to consider how to avoid that one conode can allocate unlimited amounts of RAM in another conode. They should not trust one another.

A simple solution would be that the cache has a maximum count of keys and when a set happens that would add one more than max, a random element from the cache is removed. Using Go's random map iteration would select a random key to drop from the cache.

**Comment by Gilthoniel** [comment]
I could also implement a LRU cache. As the expiration is updated with every get, most of the logic is already there, I just need to remove the oldest one when you try to set an element above the limit.

Let me know what you prefer.

**Comment by jeffallen** [comment]
In my opinion, the risk of an attacker being able to target a certain cache entry is very low, and the cost of the attack is quite low. but the cost of maintaining an LRU to defend against this risk at all times would be unreasonably high. Which is why I suggested random drop. By analogy, here is why randomness is used in network congestion avoidance: https://en.wikipedia.org/wiki/Random_early_detection

**Comment by Gilthoniel** [comment]
Right now the expiration logic is quite heavy with a loop over the items every minute. That could be improved using a double list implementation of the LRU which allows to clean only when necessary. The random access in the contrary will require to create the keys' range every time to get the first random element.
