### ISSUE TITLE
app/tesht

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#33]
Clean up the app-test-framework:
- put everything in `onet/app`
  - config and server settings
  - replace cosi-signature-check with a count-check so onet doesn't depend on cosi
  - add a library for a `cothority`-binary so that 
    - apps needing a cothority can easily incorporate it
    - tests can use a cothority with the appropriate services/protocols

**Comment by nikkolasg** [comment]
More details ? What do you mean by `fit better` ? What's wrong currently ?
