### ISSUE TITLE
log.Panic might be caused by untrusted input

### ISSUE THREAD

**Issue by jeffallen** [dedis/onet#361]
There is a log.Panic in overlay.go. It seems likely that a hand-crafted Envelope could be delivered to an overlay that has MsgType ConfigMsgId, but where the payload unmarshals to some other type.

For investigation. (And auditing for other panics that should not be possible.)

**Comment by jeffallen** [comment]
I would still like to investigate this more, but it seems like tcp.go gets encoding.go to Unmarshal the incoming message, and there the msg ID and the Go type are tightly coupled and bad input cannot decouple them.

**Comment by ineiti** [comment]
Or just remove the `log.Panic`, and IF an invalid packet gets through, it will be ignored.
