### ISSUE TITLE
Add ssl to websockets

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#383]
Current: websockets only allow HTTP connections. If somebody wants to use TLS, he'll have to use a reverse-proxy.

Wanted: add the possibility to give a private key and a certificate in the `private.toml` configuration so that the websocket can itself start a TLS authentication, if needed. As a first proposition:

```
WebsocketSSLCertificate = "file:///etc/letsencrypt/live/conode.dedis.ch/fullchain.pem"
WebsocketSSLCertificateKey = "file:///etc/letsencrypt/live/conode.dedis.ch/privkey.pem"
```

The URL can be one of:
- file:// - point to a file, relative to the `private.toml` or relative to the root if it starts with a `/`
- string:// - point to a string that holds the certificate
future use:
- skipchain://id@ip:port/cert_id`

For testing, self-signed certificates can be used.

**Comment by jeffallen** [comment]
I would like support for LetsEncrypt in the first version. @ineiti did you already discuss this with @ValentinMoullet ? I just want to be faire when I go to review the PR... don't want to add new requirements that were not there in the spec. :)

**Comment by ineiti** [comment]
@jeffallen is https://github.com/dedis/cothority/pull/1165 what you're talking about? Because I don't see how we could add letsencrypt in onet itself...

Anyway, the goal of this PR is to being able to have TLS directly in the websockets without the need for a (reverse)proxy. Adding LetsEncrypt would be a new issue, IMO. But probably 1165 covers at least part of that.

**Comment by jeffallen** [comment]
The nicest way to use LetsEncrypt with a Go server is https://godoc.org/golang.org/x/crypto/acme/autocert

You set up the autocert stuff first, then call http.ListenAndServeTLS("", ""), i.e. "no key, no cert, let autocert take care of it".

So I will add that in later. I will review PR#405 for what it is now.
