### ISSUE TITLE
add `Context.Private()`

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#432]
The current use of the `ServerIdentity` in the code is unfortunate: lots of protocols (cosi, randhound, ...) use this private key to quickly set up a signing/encrypting scheme. However, the private key for a protocol and/or a service should be set up in the service/protocol itself, and be different from the private/public key of the node. All the node (or `Context`, for that case) should provide, is a `Sign()` and a `VerifySignature()` method that allows a service/protocol to proof that the information does come from this node.

This would also solve the problem we're currently having when using `bn256` in our protocols - see dedis/kyber#314 (pi-issue).

*BUT*: as people currently _are_ using this approach, and as `TreeNodeInstance` _does_ have a `Private()` method, I've been asked (and in the need of) to add a `Context.Private()`-method, so that services also have access to that private key. It's bad, but it's what users want.

I propose to add a `Context.Private()` method that has
```
log.Warn("Deprecated use of private key - will be removed after onet.v3")
```
and add the same warning to `TreeNodeInstance.Private()`.

Furthermore, follow up on #433

**Comment by jeffallen** [comment]
As of cfe6217c4a we have different keys for different services.
