### ISSUE TITLE
Improving information about Mininet delays in README

### ISSUE THREAD

**Issue by pablo-lo** [dedis/onet#444]
Possibly related to #283.

When running simulations on Mininet, it is possible to set a delay for all runs by setting the variable in the top of the .toml file.
It is however also possible to have a delay specific to each run. This can be set e.g. as follows:

Hosts,Delay
10,10
100,50
1000,500

The README (https://github.com/dedis/onet/blob/master/simul/README.md) is currently lacking such an example. Adding one might be very helpful to future users.

**Comment by ineiti** [comment]
Feel free to create a PR ;)
