### ISSUE TITLE
Do you have any plans for p2p support?

### ISSUE THREAD

**Issue by kabelyang** [dedis/onet#477]

**Comment by jeffallen** [comment]
The ONet protocol treats all peers as equals; any server can use a send method to send to another server. For example: https://godoc.org/github.com/dedis/onet#TreeNodeInstance.SendTo

The ONet protocol depends on all nodes having a clear TCP path between them. There is no provision for having some nodes connect from behind NAT and then routing traffic inwards to them.

So depending on what you mean by p2p, yes or no.

We do not have any plans to add features related to NAT hopping. The contexts where we are using servers based on Onet (see https://github.com/dedis/cothority) do not currently require NAT hopping.

**Comment by kabelyang** [comment]
Thanks!
