### ISSUE TITLE
Error in TreeNodeInstance.DispatchChannel

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#51]
Once upon a while there was an error in DispatchChannel, but it only showed up occasionally on Travis. So there is some code waiting there to show something, just in case it happens again...

**Comment by kc1212** [comment]
There's still code regarding this issue here https://github.com/dedis/onet/blob/5bce6550583377efd53cd4080e0cc18984c2ffd3/treenode.go#L373, can they be removed?
