### ISSUE TITLE
Split statistics into multiple buckets

### ISSUE THREAD

**Issue by Gilthoniel** [dedis/onet#543]
One requirement for Protean's experiments is to be able to get statistics of a given Functional Unit and for that we need to be able to get the measures from only a subset of conodes.

simulation config file:
```toml
Buckets = "a:b c:d-e:f"
```
where a-f are a valid index according to the number of hosts. The syntax is using the Go style of slice indexing and buckets are separated by a space (so we can use `strings.Fields`). Also note the usage of `-` when you need multiple ranges for a single bucket.

The `Buckets` parameter can be specified globally or per simulation if the number of hosts change.

Note: if invalid indices are used, it won't trigger any error but the buckets won't get any statistics.

**Comment by kc1212** [comment]
how does Protean define a functional unit in cothority? if it's based on the service name then can we split the statistics based on the service?

**Comment by Gilthoniel** [comment]
After talking with Cey, the main roster will be split into smaller ones and each functional units will have its own roster so the idea from there is to provide the range of hosts for each bucket.
