### ISSUE TITLE
need to reload LE certificate

### ISSUE THREAD

**Issue by jeffallen** [dedis/onet#573]
When onet is using an externally-refreshed certificate (like when `WebSocketTLSCertificate` is set in private.toml in a conode) and the certificate is refreshed by a cronjob on the server, onet does not detect this and reload the certificate.

One solution is to just add a post-refresh job that restarts the conode. But it would be better if onet monitored the expiration date in the certificate it is using, and starts trying reloads 24 hours before.

**Comment by ineiti** [comment]
Another possibility is to use `inotify` and then reload the cert if the file changed. Even though this would only work on linux.
