### ISSUE TITLE
I am currently not planning to take this for v3, since it seems to be about stability during dev work.

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#598]
_Originally posted by @jeffallen in https://github.com/dedis/onet/pull/596#issuecomment-551824498_
> I am currently not planning to take this for v3, since it seems to be about stability during dev work.

Is it difficult to port? As we're probably bound to continue development of v3, it would be nice to have less flaky tests...

**Comment by jeffallen** [comment]
This was solved by making the tip be v3 again.
