### ISSUE TITLE
Onet v2

### ISSUE THREAD

**Issue by ineiti** [dedis/onet#84]
Epic for next steps - perhaps July 2017?

**Comment by nikkolasg** [comment]
Ok so we're not up for July 2017 ;)

We need a clear path of what do we want to achieve in this v2. Here are some of my propositions. Please feel free to comment them or dispatch them into categories (like "TODO" and "MAYBE" and "NEVER" ;) )

+ Rely on kyber.v1 once released
+ Having a configuration file with different sections for each services
+ Having each services use their own suite (from config file or default). That means:
  - Make each service unmarshal their incoming packets themselves (or using a registration mechanism)
  - Find a correct way for ProtocolInstance to know the right Suite. (If it was me alone, I'd remove the possibility of launching a Protocol only from onet, so only Services could instantiate the protocol with the correct suite)
+ TLS connections in the network stack
+ Stop using `ServerIdentity` at the onet level. Identities should be managed by the respective services who needs them and there should be only one key for one purpose. We currently have one key for every services / protocols...
